config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'splashes/index'
  get 'expenses/index'
  get 'expenses/new'
  get 'categories/index'
  get 'categories/new'
  get 'users/index'

 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splashes#index"
  resources :users  do
    member do
      get :confirm_email
    end
  end
  resources :categories, only: [:index, :show, :new, :create] do
    resources :expenses, only: [:index, :show, :new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :read, :all
    return unless user.admin?

    can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses

  validates :name, presence: true

  def total_amount
    expenses.sum(:amount)
  end
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0 }

  has_many :category_expenses, dependent: :destroy
  has_many :categories, through: :category_expenses
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable,
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :expenses

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def after_sign_up_path_for(_resource)
    categories_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.where(user_id: current_user.id).order(created_at: :desc)
    @total = {}
    @categories.each do |category|
      @total[category.id] = Expense.joins(:category_expenses)
        .where(category_expenses: { category_id: category.id })
        .where(user_id: current_user.id).sum(:amount)
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @category = Category.find_by(id: params[:category_id])
    @expenses = Expense.joins(:category_expenses).where(category_expenses:
    { category_id: params[:category_id] }).where(user_id: current_user.id).order(created_at: :desc)
    @total = Expense.joins(:category_expenses).where(category_expenses:
    { category_id: params[:category_id] }).where(user_id: current_user.id).sum(:amount)
  end

  def new; end

  def create
    @expense = Expense.new(name: params[:name], amount: params[:amount], user_id: current_user.id)

    if @expense.save!
      params[:category_ids].each do |category_id|
        CategoryExpense.create(category_id:, expense_id: @expense.id) if category_id != ''
      end
      redirect_to category_expenses_path
    else
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :category_ids)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @logo = 'logo.png'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index; end

  def new
    @user = User.new
  end

  def show; end

    # POST /users or /users.json
    def create
      @user = User.new
  
      respond_to do |format|
        if @user.save
          # Tell the UserMailer to send a welcome email after save
          UserMailer.with(user: @user).welcome_email.deliver_now
            # Redirect to the homepage or another page
            redirect_to root_url, notice: 'Thank you for signing up!'
        else
          render :new
        end
      end
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/splashes_helper.rb
module SplashesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<section class="categories_div">
<div class="category_info">
<div class="desc_container"><h1 class="text_descategory">Category</h1></div>
<div>
<strong class="category_name"><%= current_user.name %></strong><div class="link_categr"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'%></div>
</div>
</div>
<div class="container_dives">
<% @categories.each do |category|%>
      <div class="image_info">
        <div class="imag_div">
          <%= image_tag category.icon,  :alt => 'category-logo', class: "img" %>
        </div>

        <div class="info_container">
            <h1 class="text_categories">
            <%= link_to category.name, category_expenses_path(category)%></h1>
            <p class="text_time"> <%= time_ago_in_words category.created_at%> ago</p>
        </div>
            
            <div class="time_info">
            <h3 class="textcat">$ <%= @total[category.id]%></h3>
          </div>
        
        </div>
    <% end %>
  </div> 

  <div class="link">
    <%= link_to 'Add Category', new_category_path, class: 'link_path'%>
  </div> 
</section>

app/views/categories/new.html.erb
<%= form_with model: @category, url: categories_path do |f| %>
    <section class="container" >
      <div>
      <div class="desc_container"><h1 class="text_desc">Add Category</h1></div>
    <div class="field">
  
    <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder:'Name', class: "text_field" %>
  </div>
  
    
    <div class="field">
    
      <%= f.text_field :icon, autofocus: true, autocomplete: "icon", placeholder: "Icon url", class: "text_field" %>
    </div>
    <div class = "link_div">
    <div class="actions">
      <%= f.submit "Save",  class: "btn  categorybtn"%>
    </div>
    <div class ="link_category">
      <%= link_to "Back to categories", categories_path %>
    </div>
    </div>
  </div>
  </section>
  <% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/expenses/index.html.erb
<section class="expense_container">
<div class="category_info">
<div class="desc_container"><h1 class="text_descategory">Transactions</h1></div>
<div>
<strong class="category_name"><%= current_user.name %></strong><div class="link_categr"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'%></div>
</div>
</div>
<div class="escent"><h1 class="ecent_desc">Most Recent </h1></div>
<div><h5 class ="text_h">Gift Credit<span class="text_info"> $ <%= @total%></span></h5></div>
<div class="expense_div">
    <div class="container_div">
      <div class="image_div">
        <%= image_tag @category.icon, :alt => 'expense-logo', class: "img_expens"%>
      </div>
      <div class="">
        <div class="text_div">
          <h1 class="text"> <%=@category.name%></h1>
        </div>
        <div  class="time_div">
          <p><%=time_ago_in_words @category.created_at%>
        </div>
      </div>
    </div>
    <div class="info"> 
        <% @expenses.each do |expense|%>
          <div class="expense_info">
            <div class="text_expenseinfo">
              <h1 class= "time_expense"> <%= expense.name%> </h1>
              <p class="time_expense"><%= time_ago_in_words expense.created_at%> </p>
              </div>
              <div class="time_infoexpense">
              <h1 class= "time_expens">$ <%= expense.amount%> </h1>
          </div>
          </div>
        <%end%> 
        <% if @expenses.empty?%>
          <p class="text">Expenses is empty</p>
        <%end%>
      </div>
      </div>
      <div class="link">
    <%= link_to 'Add Expense', new_category_expense_path, class: 'link_path'%>
  </div> 
  <div class ="link_category">
      <%= link_to "Back to categories", categories_path %>
  </div>
</section>

app/views/expenses/new.html.erb
<div>
  <%= form_with model: @expenses, url: category_expenses_path do |f| %>
  <section class="container">
    <div class="form_div">
    <div class="desc_container"><h1 class="text_desc">Add Expenses</h1></div>
      <div class="info_div">
          <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Name', class: "text_field"
          %>
        </div>
        <div class="info_div">
          <%= f.number_field :amount, autofocus: true, autocomplete: "amount", placeholder: 'Amount',class: "text_field"
          %>
        </div>

        <div class="info_div">
      <%= f.collection_check_boxes(:category_ids, Category.where(user_id: current_user), :id, :name, {}, {:multiple => true, class: "text_expense" }) %>
      </div>

        <div class="link_div">
          <%= f.submit "Save", class:"btn"
          %>
        </div>
    </div>
   </section>
<% end %>
</div>

app/views/expenses/show.html.erb
<h1>Expenses#show</h1>
<p>Find me in app/views/expenses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splashes/index.html.erb
<section class="splash_wrapper">
<div class ="image_splash">
<%= image_tag  'logo.png', :alt =>'logo', class: "logo" %>
<div class ="link_splash">
 <div class="splashe"><%= link_to "Sign In", new_user_session_path  %></div>
<div class="splashe"><%= link_to "Sign Up", new_user_registration_path %></div>
</div>
</div>
</section>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<section  class = "splash_container">
<div class ="image_splash">
<%= image_tag  'logo.png', :alt =>'logo', class: "splash_image"%>
</div>
</section>